MovieDetail 페이지 UI 구현
wanted-pre-onboarding-fe-6th-team2/movie-trailer pull request #13
Opened 2022-09-07 15:40 UTC by yeongjuyun

## 구현 사항
- MovieDetail 페이지 UI 구현
-  movieId를 params로 받아서 id에 따른 상세페이지 구현('/movie-detail/movieId')
- react-youtube 라이브러리를 이용하여 영화 미리보기 동영상 추가(자동재생 기능은 mute 시에만 크롬에서 동작)

## 추후 구현 사항
- swr 를 적용해서 로딩, 에러 화면을 구현하려했으나 오류가 있어서 보류

## 구현 화면

<img width="823" alt="image" src="https://user-images.githubusercontent.com/79828924/188920414-54e1bfa4-b372-45f7-bbb0-06a7bcfbcbee.png">
<img width="828" alt="image" src="https://user-images.githubusercontent.com/79828924/188920464-4bb2ae9a-1505-42c4-b3fa-e77e6ed37ca2.png">

2022-09-07 16:46 UTC, HaJunRyu requested changes

2022-09-07 16:46 UTC, HaJunRyu commented on src/components/movieDetail/MovieVideo/MovieVideo.jsx
> +  const youtubeApiKey = movieDetail.video.key;
해당 변수가 담는게 youtubeApiKey가 맞나요? videoId 아닌가요?

2022-09-07 16:46 UTC, HaJunRyu commented on src/constants/route.js
> +  MOVIE_DETAIL: '/movie-detail/:movieId',
ROUTES상수는 Route를 설정할때도 사용하지만 주로 Link태그의 to props에 일관적인 문자열을 전달하고 유지보수성을 높히려는 측면에서 생각하면 상수에 `/:movieId`를 할당하는것보다 아예 비워주고 movieId는 사용하는곳에서 입력하게 하거나 해당 상수를 메서드로 바꿔주거나 하는 방법을 사용해보는건 어떨까요?

2022-09-07 16:46 UTC, HaJunRyu commented on src/pages/MovieDetail/MovieDetail.jsx
> +      const movieVideoData = await movieApiService.getMovieVideos({ movieId });
#7 PR확인해주시고 server state로 관리 부탁드립니다!

2022-09-07 16:46 UTC, HaJunRyu commented on src/pages/MovieDetail/MovieDetail.jsx
> +      });
movieDetailData에 지속적으로 접근하고 있는데 구조 분해 할당해서 setMovieDetail에서는 프로퍼티 축약표현을 사용해보시는건 어떨까요?

2022-09-08 00:06 UTC, nknkcho approved these changes

2022-09-08 00:43 UTC, wldbszpflrxj approved these changes

2022-09-08 00:52 UTC, yeongjuyun commented on src/components/movieDetail/MovieVideo/MovieVideo.jsx
> +  const youtubeApiKey = movieDetail.video.key;
넵 아이디가 더 적합할 것 같네요

2022-09-08 01:03 UTC, yeongjuyun commented on src/constants/route.js
> +  MOVIE_DETAIL: '/movie-detail/:movieId',
유지보수성을 위해서 그렇게 관리하는 게 좋겠네요

2022-09-08 01:08 UTC, yeongjuyun commented on src/pages/MovieDetail/MovieDetail.jsx
> +      });
서버데이터에 스네이크로 네이밍 된 값들이 있어서 구조분해할당을 적용하지 않았습니다.

2022-09-08 02:14 UTC, hyoungqu23 approved these changes

2022-09-08 02:21 UTC, yeongjuyun commented on src/pages/MovieDetail/MovieDetail.jsx
> +      const movieVideoData = await movieApiService.getMovieVideos({ movieId });
넵 확인했습니다.

2022-09-08 02:25 UTC, HaJunRyu commented on src/pages/MovieDetail/MovieDetail.jsx
> +      });
애매한 부분인거 같네요ㅎㅎ 함수를 통해서 처리할 수도 있겠지만 그렇게까지 하는게 맞는가? 는 스타일 차이인거 같지만 만약 기한이 촉박한 작업을 할때는 오버 엔지니어링 같은 느낌도 있다고 개인적으로 생각이 들긴해요!

그냥 set함수 위에서 구조분해할당 하면서 alias를 달아주는 형식으로도 할 수 있겠지만 뭐가 더 좋은거 같다는 영주님 스타일대로 하시면 될 거 같네요ㅎㅎ

2022-09-08 03:16 UTC, HaJunRyu approved these changes
LGTM 👍

2022-09-08 03:18 UTC, merged